config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'

  devise_for :users
  resources :books
  resources :reviews, only: [:new, :create, :destroy]
  resources :ratings, only: [:create, :destroy]

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :book


  validates :user_id, presence: true
  validates :book_id, presence: true
  validates :value, presence: true, numericality: { only_integer: true,
                                                    greater_than_or_equal_to: 1,
                                                    less_than_or_equal_to: 5 }
  validates_associated :user, :book
  validates_uniqueness_of :book_id, scope: :user_id


private


end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

  def create
    rating = current_user.ratings.build(rating_params)
    if rating.save
      flash[:notice] = "Thanks for your rating!"
    else
      flash[:alert] = "Couldn't rate the book!"
    end
    redirect_to :back
  end

  def destroy
    Rating.find_by(id: params[:id]).destroy
    flash[:notice] = "Your rating was deleted. Now you can rate again."
    redirect_to :back
  end

private

    def rating_params
      params.require(:rating).permit(:book_id, :value)
    end

    def correct_user
      rating = Rating.find(params[:id])
      unless rating.user == current_user
        flash[:alert] = "You cannot change other user's rating!"
        redirect_to book_url(rating.book )
      end
    end

end

app/helpers/ratings_helper.rb
module RatingsHelper

  def current_user_has_voted?(book)
    !current_user.rated_books.find_by(id: book.id).nil?
  end

  def current_user_rate(book)
    book.ratings.find_by(user_id: current_user.id)
  end

end

app/views/ratings/_average_rating.html.erb
Average rating:
<% if @book.ratings.any? %>
  <%= number_with_precision average_rating(@book), precision: 2 %>
<% else %>
  No rates yet!
<% end %>

app/views/ratings/_rating_form.html.erb
<% if current_user_has_voted?(@book) %>
  You rated: <%= current_user_rate(@book).value %>
  (<%= link_to 'change', rating_path(current_user_rate(@book)),
                         method: :delete, data: { confirm: 'Are you sure?' }%>)

<% else %>

  <%= form_for(@rating) do |f| %>
    <div>
      <%= f.hidden_field :book_id, value: @book.id %>
    </div>

    <div class="field">
      <%= f.number_field(:value, in: 1..5, step: 1, placeholder: "Your rating") %>
    </div>

    <div class="actions">
      <%= f.submit "Rate this book!", class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>