config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'

  devise_for :users
  resources :books
  resources :reviews, only: [:new, :create, :destroy]
  resources :ratings, only: [:create, :destroy]

end

app/models/book.rb
class Book < ApplicationRecord
  before_validation :default_values
  has_many :reviews
  has_many :ratings, dependent: :destroy
  has_many :rated_users, through: :ratings, source: :user

  validates :author, presence: true,
                     length: { maximum: 69 }
  validates :title, presence: true,
                    length: { maximum: 199 }
  validates :pub_year, presence: true,
                       numericality: { only_integer: true,
                                       greater_than_or_equal_to: 0,
                                       less_than_or_equal_to: 2020 }
  validates :description, length: { maximum: 1999 }


  def self.search(search)
    if Rails.env.production?
      where("title @@ :q or author @@ :q or description @@ :q", q: search)
    else
      where("title LIKE ? OR author LIKE ? OR description LIKE ?",
                  "%#{search}%", "%#{search}%", "%#{search}%")

    end
  end

  private

    def default_values
      if self.description.blank? || self.description.nil?
        self.description = "No description"
      end
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book added!"
      redirect_to book_path(@book)
    else
      flash[:alert] = "Couldn't add book! Try again."
      redirect_to :back
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:notice] = "Book deleted"
    redirect_to books_path
  end

  def index
    if query = params[:search]
      @books = Book.search(query)
    else
      @books = Book.all
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "Successfully updated!"
      redirect_to book_path(@book)
    else
      flash[:alert] = "Couldn't update"
      redirect_to :back
    end
  end

  def show
    @book = Book.find_by(id: params[:id])
    redirect_to books_path unless @book
    @review = Review.new(book: @book) # to use in review_form
    @rating = Rating.new(book: @book) # to use in rating_form
  end

  private

    def book_params
      params.require(:book).permit(:author, :title, :pub_year, :description)
    end

end

app/helpers/books_helper.rb
module BooksHelper

# Returns book's average rating - #TODO optimize this
  def average_rating(book)
    ratings_array = book.ratings.pluck(:value)
    ratings_array.inject(:+).to_f / ratings_array.length
  end

end

app/views/books/_book.html.erb
<!-- ID: <%= book.id %><br /> -->

<!-- CREATED AT: <%= book.created_at %><br />
UPDATED AT: <%= book.updated_at %><br /> -->


<div class="col-md-4">
  <div class="jumbotron text-center">
    <div class="single-book">
      <span class="lead"><em><%= shorten(book.title) %></em></span>
      <span><%= shorten(book.author) %></span>
      <span><%= book.pub_year %></span>
      <span><%= link_to 'more', book_url(book) %></span>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">

    <h2>Edit book</h2>
    <h3>Leave attributes you don't want to change</h3>

    <%= form_for(@book, method: :patch) do |f| %>

      <div class="field">
        <%= f.label :author %><br />
        <%= f.text_field :author, autofocus: true, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :pub_year, 'Publication year' %><br />
        <%= f.select :pub_year, 1700..2020, class: 'form-control', prompt: "Choose year" %>
      </div>

      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description,
                        placeholder: "Say a few words about this book without spoilers", class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "Submit", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="jumbotron text-center">
    <h3>All books</h3>
    <% if user_signed_in? %>
      <%= link_to 'new book', new_book_url, class: 'btn btn-primary' %>
    <% end %>
  </div>

  <% if @books.any? %>
    <div class="row">
      <% @books.each do |book| %>
        <%= render book %>
      <% end %>
    </div>
  <% else %>
    <div class="jumbotron text-center">
      <h3>No results found</h3>
    </div>
  <% end %>

</div>

app/views/books/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">

    <h2>New book</h2>

    <%= form_for(@book) do |f| %>

      <div class="field">
        <%= f.label :author %><br />
        <%= f.text_field :author, autofocus: true, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :pub_year, 'Publication year' %><br />
        <%= f.select :pub_year, 1700..2020, class: 'form-control', prompt: "Choose year" %>
      </div>

      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description,
                        placeholder: "Say a few words about this book without spoilers", class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "Submit", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="book-info jumbotron">
        <h2>Info</h2>
        <span class="lead"><em><%= @book.title %></em></span>
        <span><%= @book.author %></span>
        <span>Published in <%= @book.pub_year %></span>
        <% if user_signed_in? %>
          <div class="rating-form">
            <%= render 'ratings/rating_form' %>
          </div>
        <% end %>
        <div class="book-rating">
          <%= render 'ratings/average_rating' %>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <% if user_signed_in? %>
        <%= link_to 'delete', book_url(@book), method: :delete, data: { confirm: "Are you sure?" } %>
        <%= link_to 'edit', edit_book_url(@book) %>
      <% end %>



      <div class="jumbotron book-description">
        <h2>Description</h2>
        <span><%= @book.description %></span>
      </div>

      <div class="review-form">
      <% if user_signed_in? %>
        <%= render 'reviews/review_form' %>
      <% end %>
      </div>

      <div class="jumbotron book-reviews">
        <h2>Reviews</h2>
        <% if @book.reviews.any? %>
          <% @book.reviews.order('created_at DESC').each do |review| %>
            <%= render review %>
          <% end %>
        <% else %>
          <h4>Nobody reviewed this book yet. Be first!</h4>
        <% end %>
      </div>
   </div>
</div>