config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'

  devise_for :users
  resources :books
  resources :reviews, only: [:new, :create, :destroy]
  resources :ratings, only: [:create, :destroy]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

   def new
     @review = Review.new
   end

  def create
    review = Book.find(params[:book_id]).reviews.build(review_params)
    review.user_id = current_user.id
    if review.save
      flash[:notice] = "Your review has been successfully added"
    else
      flash[:alert] = "Couldn't add review"
    end
    redirect_to :back
  end

  def destroy
    deleted_review = Review.find(params[:id]).destroy
    related_book = deleted_review.book
    flash[:notice] = "Review deleted!"
    redirect_to book_url(related_book)
  end

private

    def review_params
      params.require(:review).permit(:content)
    end

    def correct_user
      review = Review.find(params[:id])
      unless review.user == current_user
        flash[:alert] = "You cannot delete other user's posts"
        redirect_to book_url(review.book )
      end
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<div class="container">
  <div class="jumbotron book-review">
    <div class="review-info text-right small">
      posted <%= convert_time review.created_at %>
      by <strong><%= review.user.email %></strong>
    </div>
    <div class="review-content lead">
      <%= review.content %>
    </div>
    <% if user_signed_in? && review.user == current_user%>
      <div class="review-delete">
          <%= link_to 'delete review', review_url(review), method: :delete,
                                                           data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_review_form.html.erb
    <h3>Write your review of <em><%= shorten(@book.title) %></em></h3>

    <%= form_for(@review) do |f| %>
      <div>
        <%= hidden_field_tag :book_id, @book.id %>
      </div>

      <div class="field">
        <!-- <%= f.label :content %><br /> -->
        <%= f.text_area :content, class: 'form-control', placeholder: "Write here..." %>
      </div>

      <div class="actions">
        <%= f.submit "Submit review", class: 'btn btn-primary' %>
      </div>
    <% end %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>