config/routes.rb
Rails.application.routes.draw do


  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: 'static_pages#help'

  devise_for :users
  resources :books
  resources :reviews, only: [:new, :create, :destroy]
  resources :ratings, only: [:create, :destroy]

end

app/views/layouts/_fonts.html.erb
<!-- font-family: 'Pacifico', cursive; -->
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by
    <a href="https://github.com/ahawrylak"> Adrian Hawrylak</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
      <li><%= link_to 'Help', help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to 'Libre', root_path, class: 'logo-nav navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= render 'layouts/searchbox' %>
        </li>
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, '#', class: 'mark' %>
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        <% end %>
        <li>
          <%= link_to 'All books', books_path %>
        </li>



        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Contact', contact_path %></li>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Help', help_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_searchbox.html.erb
<div class="searchbox">
  <%= form_tag(books_path, method: :get, id: "search-form") do %>
    <%= search_field_tag :search, params[:search], class: "form-control",
                                                   placeholder: "Search for titles/authors" %>
    <%= submit_tag "Search", hidden: true %>

  <% end %>
</div>


<!--
<form class="form-inline">
  <div class="form-group">
    <input type="search" class="form-control" id="search-form" placeholder="Search for titles/authors">
  </div>
</form> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/fonts' %>

    <title>Libre</title>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |msg_type, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>